Automate release process
Update GitHub workflow to automatically release
when tagged with v* (following successful tests).

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,26 +1,26 @@
-name: test
+name: ci-cd
 
 on:
   push:
   pull_request:
   workflow_dispatch:
   schedule:
-    # Weekly build (on branch main) every Thursday at 12:00 UTC.
+    # Weekly test (on branch main) every Thursday at 12:00 UTC.
     # (Used to monitor compatibility with ESP APIs and other dependencies.)
     - cron: '0 12 * * 4'
 
 
 jobs:
   skip_duplicate_runs:
-    # Avoid running the tests twice on the same code
-    # (particularly live integration tests that eat up ESP test quota)
-    runs-on: ubuntu-18.04
+    # Avoid running the live integration tests twice on the same code
+    # (to conserve limited sending quotas in the live ESP test accounts)
+    runs-on: ubuntu-20.04
     outputs:
       should_skip: ${{ steps.skip_check.outputs.should_skip }}
     steps:
       - id: skip_check
-        # uses: fkirc/skip-duplicate-actions@v3.3.0
-        uses: fkirc/skip-duplicate-actions@ea548f2a2a08c55dcb111418ca62181f7887e297
+        # uses: fkirc/skip-duplicate-actions@v3.4.0
+        uses: fkirc/skip-duplicate-actions@4c656bbdb6906310fa6213604828008bc28fe55d
         with:
           concurrent_skipping: "same_content"
           skip_after_successful_duplicate: "true"
@@ -29,9 +29,8 @@ jobs:
 
   test:
     name: ${{ matrix.config.tox }} ${{ matrix.config.options }}
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     needs: skip_duplicate_runs
-    if: ${{ needs.skip_duplicate_runs.outputs.should_skip != 'true' }}
     timeout-minutes: 15
     strategy:
       fail-fast: false
@@ -105,7 +104,7 @@ jobs:
         # for installing/running tox
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: 3.9
       - name: Install tox
         run: |
           set -x
@@ -120,7 +119,11 @@ jobs:
         env:
           CONTINUOUS_INTEGRATION: true
           TOX_FORCE_IGNORE_OUTCOME: false
-          ANYMAIL_RUN_LIVE_TESTS: ${{ contains( matrix.config.options, 'run-live-tests' ) }}
+          ANYMAIL_RUN_LIVE_TESTS: >-
+            ${{
+            contains( matrix.config.options, 'run-live-tests' )
+            && needs.skip_duplicate_runs.outputs.should_skip != 'true'
+            }}
           ANYMAIL_TEST_AMAZON_SES_ACCESS_KEY_ID: ${{ secrets.ANYMAIL_TEST_AMAZON_SES_ACCESS_KEY_ID }}
           ANYMAIL_TEST_AMAZON_SES_REGION_NAME: ${{ secrets.ANYMAIL_TEST_AMAZON_SES_REGION_NAME }}
           ANYMAIL_TEST_AMAZON_SES_SECRET_ACCESS_KEY: ${{ secrets.ANYMAIL_TEST_AMAZON_SES_SECRET_ACCESS_KEY }}
@@ -135,3 +138,49 @@ jobs:
           ANYMAIL_TEST_SENDGRID_TEMPLATE_ID: ${{ secrets.ANYMAIL_TEST_SENDGRID_TEMPLATE_ID }}
           ANYMAIL_TEST_SENDINBLUE_API_KEY: ${{ secrets.ANYMAIL_TEST_SENDINBLUE_API_KEY }}
           ANYMAIL_TEST_SPARKPOST_API_KEY: ${{ secrets.ANYMAIL_TEST_SPARKPOST_API_KEY }}
+
+  release:
+    runs-on: ubuntu-20.04
+    needs: test
+    if: >-
+      startsWith(github.ref, 'refs/tags/v')
+      && contains(['push', 'workflow_dispatch'], github.event_name)
+    steps:
+      - name: Get code
+        uses: actions/checkout@v2
+      - name: Setup default Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+      - name: Check package version
+        id: version
+        run: |
+          PACKAGE_VERSION="v$(python setup.py --version)"
+          TAG_VERSION="${GITHUB_REF#refs/tags/}"
+          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
+            echo "::error ::package version '$PACKAGE_VERSION' does not match git tag '$TAG_VERSION'"
+            exit 1
+          fi
+          echo "::set-output name=tag::$TAG_VERSION"
+          echo "::set-output name=anchor::${TAG_VERSION//[^[:alnum:]]/-}"
+      - name: Build
+        run: |
+          rm -rf build dist django_anymail.egg-info
+          python setup.py sdist bdist_wheel
+          twine check dist/*
+      - name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          user: __token__
+          password: ${{ secrets.PYPI_API_TOKEN }}
+          repository_url: https://test.pypi.org/legacy/  # TODO: remove for production
+      - name: Publish release to Github
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          TAG: ${{ steps.version.outputs.tag }}
+          TITLE: ${{ steps.version.outputs.tag }}
+          DRAFT: true  # TODO: remove for production
+          NOTES: |
+            [Changelog](https://anymail.readthedocs.io/en/stable/changelog/#${{ steps.version.outputs.anchor }})
+        run: |
+          gh release create "$TAG" --title "$TITLE" --notes "$NOTES" "${DRAFT:+--draft}"
